apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: httpd:alpine3.19
        name: httpd
        #cool thing is if you deploy, you'll see it not brin them all down
        #it'll just keep trying the two 
        command: ["/bin/bash", "c"] #override default command
        args: ["sleep 5; exit 1"] #lseep 30 seconds then exit, mimic crash
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
status: {}
